name: etkinlikapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  #Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.6
 
  #UIAPPKIT
  animate_do: ^3.3.4
  stylish_bottom_bar: ^1.0.3
  animated_custom_dropdown: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  google_nav_bar: ^5.0.6
  shimmer: ^3.0.0
  slide_to_act: ^2.0.2
  liquid_pull_to_refresh: ^3.0.1
  grouped_list: ^5.1.2 
  roundcheckbox: ^2.0.5
  loading_animation_widget:
  curved_navigation_bar: ^1.0.3

  #locale data
  shared_preferences: ^2.2.3

  #state
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  #network
  dio: ^5.4.2+1
  
  #Codegen
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.8.1

  #file
  file_picker: ^8.0.0+1

  #font
  google_fonts: ^6.2.0

  #maps
  google_maps_flutter: ^2.5.3
  location: ^6.0.1

  #Core
  very_good_analysis: ^5.1.0
  intl: ^0.19.0
  equatable: ^2.0.5
 
  codegen:
    path: module/codegen

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 

  #network
  json_serializable: ^6.7.1

  #build
  build_runner: ^2.4.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/json/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
